import { preload } from "react-dom";
import Countdown from "./Countdown";
import HeroScrollFx from "./HeroScrollFx";
import { DISCORD_URL, LAUNCH_DATE } from "@/lib/config";

// Hero cityscape (LCP) integration flag. The AVIF/WebP source files are
// generated by the user from docs/technical/hero-cityscape-prompt.md — see
// docs/technical/frontend-rg-web.md §Asset provenance for exact drop-in paths
// and specs. Until those files exist:
//   - #hero-art renders a dusk gradient fallback (intentional, not broken).
//   - the wordmark (.mask-base) uses its --mask-art-fallback gradient, so the
//     "GTA 6" letters stay visible (not transparent).
//   - no preload <link>s are emitted (there is nothing to preload yet).
// Flip to `true` (and set --mask-art + <picture> sources below) in a later
// commit once the assets land.
const HERO_CITYSCAPE_READY = false;

const HERO_ART_16X9 = "/hero/cityscape-16x9.avif";
const HERO_ART_9X16 = "/hero/cityscape-9x16.avif";

const jsonLdEvent = {
  "@context": "https://schema.org",
  "@type": "Event",
  name: "Lanzamiento de Grand Theft Auto 6",
  startDate: LAUNCH_DATE,
  description:
    "Grand Theft Auto 6 llega a PlayStation 5 y Xbox Series X|S el 19 de noviembre de 2026. La cuenta regresiva de la comunidad Radar GTA.",
  eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
  location: {
    "@type": "Place",
    name: "Leonida",
  },
};

export default function Hero() {
  if (HERO_CITYSCAPE_READY) {
    // Media-scoped preloads: 16:9 srcset for desktop (>=768px), 9:16
    // art-directed crop for mobile. NOT next/image's preload prop (cannot
    // art-direct crops or carry a media attribute; the legacy prop it replaced
    // is deprecated in Next 16). Deliberate deviation — see ADR 0009.
    preload(HERO_ART_16X9, {
      as: "image",
      media: "(min-width: 768px)",
      imageSrcSet:
        "/hero/cityscape-16x9-640.avif 640w, /hero/cityscape-16x9-1280.avif 1280w, /hero/cityscape-16x9-1920.avif 1920w, /hero/cityscape-16x9-2400.avif 2400w",
      imageSizes: "100vw",
      fetchPriority: "high",
    });
    preload(HERO_ART_9X16, {
      as: "image",
      media: "(max-width: 767px)",
      imageSrcSet:
        "/hero/cityscape-9x16-640.avif 640w, /hero/cityscape-9x16-1280.avif 1280w, /hero/cityscape-9x16-1920.avif 1920w",
      imageSizes: "100vw",
      fetchPriority: "high",
    });
  }

  return (
    <section
      id="hero"
      className="relative isolate flex min-h-screen flex-col items-center justify-center overflow-hidden px-6 py-24 text-center"
    >
      <HeroScrollFx />

      {/* Art layer (z 0). Cityscape fills the hero; masked by the wordmark above. */}
      <div id="hero-art" aria-hidden="true" className="hero-art">
        <div className="hero-ambient absolute inset-0" />
        {HERO_CITYSCAPE_READY ? (
          <picture>
            <source
              media="(max-width: 767px)"
              srcSet="/hero/cityscape-9x16-640.avif 640w, /hero/cityscape-9x16-1280.avif 1280w, /hero/cityscape-9x16-1920.avif 1920w"
              sizes="100vw"
              type="image/avif"
            />
            <source
              srcSet="/hero/cityscape-16x9-640.avif 640w, /hero/cityscape-16x9-1280.avif 1280w, /hero/cityscape-16x9-1920.avif 1920w, /hero/cityscape-16x9-2400.avif 2400w"
              sizes="100vw"
              type="image/avif"
            />
            {/* WebP fallback for the 16:9 source (last source wins on old browsers). */}
            <source
              srcSet="/hero/cityscape-16x9-1280.webp 1280w, /hero/cityscape-16x9-2400.webp 2400w"
              sizes="100vw"
              type="image/webp"
            />
            <img
              src="/hero/cityscape-16x9-1280.webp"
              alt=""
              fetchPriority="high"
              decoding="async"
              className="absolute inset-0 h-full w-full object-cover"
            />
          </picture>
        ) : (
          <div className="hero-art-fallback absolute inset-0" />
        )}
      </div>

      {/* Wash layer (z 30) — fades in during P2 (40-70% scroll). */}
      <div id="hero-wash" aria-hidden="true" className="hero-wash" />

      {/* Wordmark window (z 10) — text-clip mask over the cityscape. */}
      <div id="hero-title-mask" className="relative z-10 mb-6">
        <h1
          className="mask-base font-display text-[clamp(5rem,22vw,15rem)] uppercase leading-none tracking-tight"
          style={
            HERO_CITYSCAPE_READY
              ? ({ "--mask-art": `url(${HERO_ART_16X9})` } as React.CSSProperties)
              : undefined
          }
        >
          GTA 6
        </h1>
      </div>

      {/* Content layer (z 20) — parallax-out during P3 (70-100% scroll). */}
      <div id="hero-content" className="relative z-20 flex flex-col items-center">
        <span className="eyebrow mb-6">Comunidad GTA 6 en español</span>

        <p className="mb-10 max-w-2xl text-balance text-lg text-muted sm:text-xl">
          Vice City. Leonida. Cuando el sol se apaga y el neón enciende, todos
          tienen algo que ganar — y más que perder.
        </p>

        <div id="hero-countdown" className="mb-12">
          <Countdown />
        </div>

        <div className="flex flex-col items-center gap-4 sm:flex-row">
          <a
            href={DISCORD_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="btn-primary"
          >
            Únete al Discord
          </a>
          <a href="#crews" className="btn-ghost">
            Registra tu Crew
          </a>
        </div>
      </div>

      {/* Scroll cue (z 20) — fades early (0.15-0.30) on scroll. */}
      <div id="hero-cue" className="hero-cue">
        <span className="hero-cue-line" aria-hidden="true" />
        <span className="sr-only">Scroll</span>
      </div>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdEvent) }}
      />
    </section>
  );
}
